services:
  - type: web
    name: nexus-platform-backend
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      playwright install chromium
      playwright install --with-deps
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false