"""
Revision ID: ebf4eb0629fe
Revises: 9c6844d6432a
Create Date: 2025-08-25 06:15:43.546327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf4eb0629fe'
down_revision: Union[str, None] = '9c6844d6432a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message_metadata', sa.Text(), nullable=True))
    op.drop_column('chat_messages', 'extra_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chat_messages', 'message_metadata')
    # ### end Alembic commands ###
